# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-17 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('courseNumber', models.IntegerField(blank=True, default=0)),
                ('instructorName', models.CharField(blank=True, default='', max_length=60)),
                ('duration', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
